name: ðŸš€ Deploy App to VPS

on:
  push:
    branches:
      - production

jobs:
  deploy:
    name: ðŸ› ï¸ Build & Deploy
    runs-on: ubuntu-latest

    steps:
      - name: â¬‡ï¸ Checkout code
        uses: actions/checkout@v3

      - name: ðŸ” Setup SSH key
        run: |
          echo "${{ secrets.HOST_SSH_KEY }}" > key.pem
          chmod 600 key.pem

      - name: ðŸš€ Deploy to Hostinger VPS
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ${{ secrets.HOST_USERNAME }}@${{ secrets.HOST_SERVER_IP }} << 'EOF'
            cd /root/app/

            git pull origin production

            cd ..

            docker-compose down
            docker-compose up -d --build
          EOF